"""Autogenerate migration for recent model changes

Revision ID: 90367d925e03
Revises: 6242c5522375
Create Date: 2025-04-08 11:38:30.649690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '90367d925e03'
down_revision: Union[str, None] = '6242c5522375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Drop the temporary table if it exists from a previous failed migration
    temp_table_name = '_alembic_tmp_billingperiod'
    if temp_table_name in inspector.get_table_names():
        op.drop_table(temp_table_name)
        
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billingperiod', schema=None) as batch_op:
        batch_op.drop_constraint('fk_billingperiod_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_billingperiod_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('daily_usage_summary', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_usage_summary_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_daily_usage_summary_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('flow_wizard_metadata', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_flow_wizard_metadata_id', ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('kbusagedetail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_kbusagedetail_usage_record_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_kbusagedetail_usage_record_id_usagerecord', 'usagerecord', ['usage_record_id'], ['id'])

    with op.batch_alter_table('tokenusagedetail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tokenusagedetail_usage_record_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_tokenusagedetail_usage_record_id_usagerecord', 'usagerecord', ['usage_record_id'], ['id'])

    with op.batch_alter_table('toolusagedetail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_toolusagedetail_usage_record_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_toolusagedetail_usage_record_id_usagerecord', 'usagerecord', ['usage_record_id'], ['id'])

    with op.batch_alter_table('usagerecord', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usagerecord_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_usagerecord_flow_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_usagerecord_flow_id_flow', 'flow', ['flow_id'], ['id'])
        batch_op.create_foreign_key('fk_usagerecord_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usagerecord', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usagerecord_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_usagerecord_flow_id_flow', type_='foreignkey')
        batch_op.create_foreign_key('fk_usagerecord_flow_id', 'flow', ['flow_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_usagerecord_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('toolusagedetail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_toolusagedetail_usage_record_id_usagerecord', type_='foreignkey')
        batch_op.create_foreign_key('fk_toolusagedetail_usage_record_id', 'usagerecord', ['usage_record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tokenusagedetail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tokenusagedetail_usage_record_id_usagerecord', type_='foreignkey')
        batch_op.create_foreign_key('fk_tokenusagedetail_usage_record_id', 'usagerecord', ['usage_record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('kbusagedetail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_kbusagedetail_usage_record_id_usagerecord', type_='foreignkey')
        batch_op.create_foreign_key('fk_kbusagedetail_usage_record_id', 'usagerecord', ['usage_record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('flow_wizard_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('uq_flow_wizard_metadata_id', type_='unique')

    with op.batch_alter_table('daily_usage_summary', schema=None) as batch_op:
        batch_op.drop_constraint('fk_daily_usage_summary_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_daily_usage_summary_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('billingperiod', schema=None) as batch_op:
        batch_op.drop_constraint('fk_billingperiod_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('fk_billingperiod_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
