"""Modify id and flow_id types in flow_wizard_metadata to Uuid

Revision ID: d9591af34f0e
Revises: f171002780b2
Create Date: 2025-04-08 23:07:58.615999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'd9591af34f0e'
down_revision: Union[str, None] = 'f171002780b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_wizard_metadata', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('flow_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_wizard_metadata', schema=None) as batch_op:
        batch_op.alter_column('flow_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
