"""Add foreign key constraint to user.subscription_plan_id

Revision ID: f171002780b2
Revises: 90367d925e03
Create Date: 2025-04-08 11:43:30.960689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'f171002780b2'
down_revision: Union[str, None] = '90367d925e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_subscription_plan_id_subscriptionplan', 'subscriptionplan', ['subscription_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_subscription_plan_id_subscriptionplan', type_='foreignkey')

    # ### end Alembic commands ###
